package icu.pboymt.mayer.assets

import androidx.annotation.Keep

@Suppress("unused", "SpellCheckingInspection")
@Keep
object Tpls {
    const val BOSS_LEVEL_HIGH_PLUS = "templates/boss-level-high-plus.png"
    const val BOSS_LEVEL_HIGH = "templates/boss-level-high.png"
    const val BOSS_LEVEL_MIDDLE = "templates/boss-level-middle.png"
    const val BOSS_LEVEL_SUPER = "templates/boss-level-super.png"
    const val BOSS_LIST_WAITING = "templates/boss-list-waiting.png"
    const val BOSS_TARGET_ADMINISTRATOR = "templates/boss-target-administrator.png"
    const val BOSS_TARGET_ANCIENT_GOLEM = "templates/boss-target-ancient-golem.png"
    const val BOSS_TARGET_ARCH_ACCURSED = "templates/boss-target-arch-accursed.png"
    const val BOSS_TARGET_HERMIT_KING = "templates/boss-target-hermit-king.png"
    const val BOSS_TARGET_JACK_O_LANTERN_HIGH_PLUS = "templates/boss-target-jack-o-lantern-high-plus.png"
    const val BOSS_TARGET_JACK_O_LANTERN_SUPER = "templates/boss-target-jack-o-lantern-super.png"
    const val BOSS_TARGET_OROCHI = "templates/boss-target-orochi.png"
    const val BOSS_TARGET_REGITARE = "templates/boss-target-regitare.png"
    const val BOSS_TARGET_WHITETAIL = "templates/boss-target-whitetail.png"
    const val BTN_ABANDON = "templates/btn-abandon.png"
    const val BTN_BATTLE_AGAIN = "templates/btn-battle-again.png"
    const val BTN_BATTLE_AUTO_SKILL_ON = "templates/btn-battle-auto-skill-on.png"
    const val BTN_CANCEL = "templates/btn-cancel.png"
    const val BTN_CONTINUE = "templates/btn-continue.png"
    const val BTN_LEAVE_ROOM = "templates/btn-leave-room.png"
    const val BTN_OK = "templates/btn-ok.png"
    const val BTN_RETURN_ROOM = "templates/btn-return-room.png"
    const val BTN_RING_JOIN_ACCEPT_N = "templates/btn-ring-join-accept-n.png"
    const val BTN_RING_JOIN_ACCEPT = "templates/btn-ring-join-accept.png"
    const val BTN_RING_JOIN_REJECT = "templates/btn-ring-join-reject.png"
    const val BTN_SINGLE_BATTLE_START = "templates/btn-single-battle-start.png"
    const val BTN_STAMINA_GSMALL = "templates/btn-stamina-gsmall.png"
    const val BTN_STAMINA_LARGE = "templates/btn-stamina-large.png"
    const val BTN_STAMINA_MEDIUM = "templates/btn-stamina-medium.png"
    const val BTN_STAMINA_SMALL = "templates/btn-stamina-small.png"
    const val BTN_STAMINA_STONE = "templates/btn-stamina-stone.png"
    const val BTN_STAMINA_XNEWYEAR = "templates/btn-stamina-xnewyear.png"
    const val BTN_USE = "templates/btn-use.png"
    const val BUYBACK = "templates/buyback.png"
    const val FINISH_ALERT_LOST_CONNECTION = "templates/finish-alert-lost-connection.png"
    const val FINISH_ALERT_TEAM_DISMISS = "templates/finish-alert-team-dismiss.png"
    const val HOME_BTN_CHAPTER = "templates/home-btn-chapter.png"
    const val LABEL_LACK_STAMINA = "templates/label-lack-stamina.png"
    const val LABEL_LEVEL_UP = "templates/label-level-up.png"
    const val LABEL_STAMINA_OK = "templates/label-stamina-ok.png"
    const val RING_N = "templates/ring-n.png"
    const val RING = "templates/ring.png"
    const val WAITING_ROOM_AUTO_CONTINUE_NO = "templates/waiting-room-auto-continue-no.png"
    const val WAITING_ROOM_AUTO_CONTINUE_YES = "templates/waiting-room-auto-continue-yes.png"
    const val WAITING_ROOM_READY_NO = "templates/waiting-room-ready-no.png"
    const val WAITING_ROOM_READY_YES = "templates/waiting-room-ready-yes.png"
    const val WAITING_ROOM_TEAM_FORM = "templates/waiting-room-team-form.png"
}
