name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  OPENCV_VERSION: 4.7.0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Cache OpenCV4Android SDK
        id: cache-opencv
        uses: actions/cache@v2
        with:
          path: ./opencv
          key: opencv-for-android-${{ env.OPENCV_VERSION }}
          restore-keys: |
            opencv-for-android-

      - if: ${{ steps.cache-opencv.outputs.cache-hit != 'true' }}
        name: Download OpenCV4Android and extract to :opencv
        run: |
          wget https://github.com/opencv/opencv/releases/download/$OPENCV_VERSION/opencv-$OPENCV_VERSION-android-sdk.zip -O opencv.zip
          unzip opencv.zip sdk/* -d opencv

      - name: Copy opencv.build.gradle.txt to opencv/build.gradle
        run: cp opencv.build.gradle.txt opencv/build.gradle

      - name: Install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;23.1.7779620" --sdk_root=${ANDROID_SDK_ROOT} &> /dev/null

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          arguments: assembleRelease

      #    - name: Grant execute permission for gradlew
      #      run: chmod +x gradlew
      #    - name: Build with Gradle
      #      run: ./gradlew build

      - name: Update ARM64
        uses: actions/upload-artifact@v3
        with:
          name: arm64-v8a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-arm64-v8a-release.apk

      - name: Update x86_64
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-${{ github.sha }}
          path: app/build/outputs/apk/release/app-x86_64-release.apk

      - name: Update ARM32
        uses: actions/upload-artifact@v3
        with:
          name: armeabi-v7a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-armeabi-v7a-release.apk

      - name: Update x86
        uses: actions/upload-artifact@v3
        with:
          name: x86-${{ github.sha }}
          path: app/build/outputs/apk/release/app-x86-release.apk

      - name: Update mapping
        uses: actions/upload-artifact@v3
        with:
          name: mapping-${{ github.sha }}
          path: app/build/outputs/mapping/release/mapping.txt
          retention-days: 5